INSERT 
  INTO STORAGE D
(
  D.PLAYER_NAME
, D.INGRE_NO
, D.INGRE_CNT
) 
(
SELECT DISTINCT C.PLAYER_NAME
     , B.INGRE_NO
     , 10
  FROM PLAYER_RECIPE C
  JOIN RECIPE_INGRE  B ON ( B.RECIPE_NO = C.RECIPE_NO )
);

SELECT DISTINCT C.PLAYER_NAME
     , B.INGRE_NO
     , 10
  FROM PLAYER_RECIPE C
  JOIN RECIPE_INGRE  B ON ( B.RECIPE_NO = C.RECIPE_NO );
